AdventCode.Day1ElfCalories.Task.Run();
AdventCode.Day2RockPaperScissors.Task.Run();
AdventCode.Day3RucksackReorg.Task.Run();
AdventCode.Day4CampCleanup.Task.Run();
AdventOfCode.Day5SupplyStacks.Task.Run();
AdventOfCode.Day6TuningTrouble.Task.Run();
AdventCode.Day7NoSpaceLeftOnDevice.Task.Run();
AdventOfCode.Day8TreetopTreeHouse.Task.Run();
AdventOfCode.Day9RopeBridge.Task.Run();
